# Generated by Django 3.2.15 on 2022-12-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceXLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=16, verbose_name='Flight Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('booster_version', models.CharField(max_length=128, verbose_name='Booster Version')),
                ('launch_site', models.CharField(max_length=64, verbose_name='Launch Site')),
                ('payload', models.CharField(max_length=256, verbose_name='Payload')),
                ('payload_weight', models.CharField(blank=True, max_length=256, verbose_name='Payload Weight')),
                ('orbit', models.CharField(max_length=128, verbose_name='Orbit')),
                ('customer', models.CharField(max_length=256, verbose_name='Customer')),
                ('mission_result', models.CharField(max_length=256, verbose_name='Mission Result')),
                ('landing_result', models.CharField(max_length=256, verbose_name='Landing Result')),
            ],
        ),
    ]
